### PR TITLE
[Enhancement] Minimum Character status to run a command

### PR DESCRIPTION
**Pull request by jhonynet**
Here we check a character status before run specific command. To execute a chat command, character status must be equal or greater than the minimum character requirement of desired command.
And change if repetition with a switch

### CODE REVIEW

**Comment by jhonynet** [comment]
i don't know why this error happens, I'm using Osx 10.14.6 64 bits and 3.1.100 sdk.

In my notebooks runs fine and in client work the command and the validation.

`Finished building project: MUnique.OpenMU.GameLogic. Succeeded: True. Errors: 0. Warnings: 8`

any idea?

**Comment by jhonynet** [comment]
Screen Shot 2020-03-11 at 00 39 50

**Comment by sven-n** [comment]
Still this error:
```
PlugIns\CreateItemChatCommandPlugIn.cs(26,48): error CS0246: The type or namespace name 'IChatCommandPlugIn' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\GameLogic\MUnique.OpenMU.GameLogic.csproj]
```
I have no idea... I cloned your repo and on my machine it builds without errors as well.
I also can't find the file ```PlugIns\CreateItemChatCommandPlugIn.cs``` in this path in my checkout or on the GitHub interface

**Comment by jhonynet** [comment]
ok. the quality review fails because a //todo comment.
should i remove it or will merge anyway?

**Comment by sven-n** [comment]
Please remove/resolve them. Otherwise it can be forgotten to solve these TODOs ;)

**Comment by jhonynet** [comment]
done.
Increased minimum status required to game master, now we should set as GM the test accounts, otherwise /teleport and /item will not work

**Comment by sven-n** [comment]
Okay, somehow stuff went wrong - I fixed them ;)

I added the test account "testgm" with GameMaster characters to the data initialization

**Pull request merged**
