### PR TITLE
Added ItemRepairPrice calc

### PR DESCRIPTION
**Pull request by And3rsL**
Add basic repair price calculation, not 100% same as client shows but is ok for now

-- Need to find NPC repair discount

### CODE REVIEW

**Comment by sven-n** [comment]
Nice, thanks. I‘ll look at it soon :)

**Comment by sven-n** [comment]
In game the npc(e.g. at Hanzo the Blacksmith) is 2.5x cheaper. Example: normal repair: 2500, at npc: 1000

I didn’t check yet if there is another discount when repairing the whole inventory at once.

I think the slight differences could also come from a missing call to RoundPrice.

In my limited time only did some quick checks with high excellent items and I think there might be a general error in the item price calculation :-/ I’ll take a look next week again.

**Comment by sven-n** [comment]
why did you close it? ;)

**Comment by And3rsL** [comment]
i think i messed up with github and deleted it! 
i will push itemprice when its 100% done and tested

sry

**Comment by sven-n** [comment]
No problem, I’ll work on it using your code as a base :)

**Pull request closed without merging**
