### PR TITLE
[Enhancement] Move chat commands to folder

### PR DESCRIPTION
**Pull request by jhonynet**
due the long list of future commands i think is a good idea to move to separated folder

### CODE REVIEW

**Comment by jhonynet** [comment]
I can't see the failed log :S

**Comment by sven-n** [comment]
Me too, I’m not on my desk atm :(
Have you tried building the whole solution?

Sorry for the inconvenience

**Comment by jhonynet** [comment]
Yes, it builds in my local.
Can we re-dispatch checks from here without any push?

**Comment by sven-n** [comment]
Error in the Azure Pipeline Log:
```
PlugIns\CreateItemChatCommandPlugIn.cs(26,48): error CS0246: The type or namespace name 'IChatCommandPlugIn' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\GameLogic\MUnique.OpenMU.GameLogic.csproj]
```

**Comment by sven-n** [comment]
I think the original CreateItemChatCommandPlugIn.cs wasn't committed as moved or deleted, that's why the error occurs

**Comment by jhonynet** [comment]
Ok, now with the log i can fix it
Thanks you!

**Pull request closed without merging**
