### PR TITLE
[Fix] Startup args -demo and -reinit

### PR DESCRIPTION
**Pull request by afrokick**
Must be one dash instead of double.

### CODE REVIEW

**Comment by sven-n** [comment]
Double dashes are intended - if you want the demo mode or a reinit, just remove a dash. Usually, you'd not want to reinit every time, for example.
Alternatively, we could add more profiles which have corresponding names.

**Comment by afrokick** [comment]
Yeah, I have created another profile and it is more clearly for users

**Comment by afrokick** [comment]
```json
{
  "profiles": {
    "MUnique.OpenMU.Startup": {
      "commandName": "Project",
      "commandLineArgs": "-autostart -resolveIp:local",
      "applicationUrl": "http://localhost",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:80"
      }
    },
    "StartupReinit": {
      "commandName": "Project",
      "commandLineArgs": "-autostart -resolveIp:local -demo -reinit",
      "applicationUrl": "http://localhost",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:80"
      }
    }
  }
}
```

How about this one?

**Comment by sven-n** [comment]
Well, -reinit and -demo in one line makes no sense, because in demo-mode, it's always doing a reinit in memory ;-)
My proposal:
```json
{
  "profiles": {
    "MUnique.OpenMU.Startup": {
      "commandName": "Project",
      "commandLineArgs": "-autostart -resolveIp:local",
      "applicationUrl": "http://localhost",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:80"
      }
    },
    "Startup with DB reinit": {
      "commandName": "Project",
      "commandLineArgs": "-autostart -resolveIp:local -reinit",
      "applicationUrl": "http://localhost",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:80"
      }
    },
    "Startup in demo mode": {
      "commandName": "Project",
      "commandLineArgs": "-autostart -resolveIp:local -demo",
      "applicationUrl": "http://localhost",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ASPNETCORE_URLS": "http://+:80"
      }
    }
  }
}
```

**Pull request merged**
