### PR TITLE
Trap Support

### PR DESCRIPTION
**Pull request by And3rsL**
It creates basic trap support, at least they dont walk around :)

### CODE REVIEW

**Comment by And3rsL** [comment]
i just noticed you changed somethings in EntityDataContextModelSnapshot, you should fix it before merge, but add TrapType

**Comment by sven-n** [comment]
Thanks, I’ll check it soon.
I somehow remember a similar issue a long time ago - will try to find it ;)

**Comment by sven-n** [comment]
I'm just checking your PR. It works, but I'd like to change how the correct behavior is defined in the data and created in the logic.
I found a flaw in the initial code design, which I'd like to fix with this extension, as well. Currently, we have just an interface "IAttackable" for objects which can receive attacks, but also perform attacks. In case of some objects, this is not sufficient. Traps can't be attacked, but only attack. (Castle) Gates or Statues can only be attacked, but not attack.
So, I'd like to introduce the interface IAttacker. Since this involves a lot of code changes, I'll do it myself. Once I'm done, I'll push it into this PR :)

**Comment by sven-n** [comment]
@And3rsL have you got some attack animations and working attacks with your changes?
I found that some traps (Lost Tower, Meteorite Traps) seem to cause damage, but I see no animations :-(
And some other traps don't attack at all (Fire Traps, Dungeon).

I put a lot of changes into this PR. However, I think some things in the attack logic still needs some fine tuning ;-)

**Comment by And3rsL** [comment]
I think meteorite traps and all area attack in general just cast spells.. but maybe I'm wrong

**Comment by sven-n** [comment]
Two traps cast a flame skill according to the Monsters.txt, others don't.
So, I think it makes sense to solve #177 within this PR here, too.

**Comment by sven-n** [comment]
I think I got it working :) I get hits and skill animations from the traps and monsters.
Could you do a quick test in game?

**Pull request merged**
